"""Add inventory ledger and warehouse models

Revision ID: 92f49cdb385f
Revises: a0b59cdc0c24
Create Date: 2026-06-11 02:52:00.528021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f49cdb385f'
down_revision: Union[str, Sequence[str], None] = 'a0b59cdc0c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TRANSFER', 'ADJUSTMENT', 'PURCHASE', name='approvaltype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('STOCK_RECEIVED', 'STOCK_RESERVED', 'STOCK_RELEASED', 'STOCK_TRANSFERRED', 'STOCK_ADJUSTED', 'STOCK_DAMAGED', 'STOCK_RETURNED', 'STOCK_SOLD', name='eventtype'), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('before_value', sa.Integer(), nullable=False),
    sa.Column('after_value', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_events_product_id'), 'inventory_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_events_timestamp'), 'inventory_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_inventory_events_warehouse_id'), 'inventory_events', ['warehouse_id'], unique=False)
    op.add_column('products', sa.Column('expected_runout_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('recommended_reorder_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('supplier_recommendation', sa.String(), nullable=True))
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'supplier_recommendation')
    op.drop_column('products', 'recommended_reorder_quantity')
    op.drop_column('products', 'expected_runout_date')
    op.drop_index(op.f('ix_inventory_events_warehouse_id'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_timestamp'), table_name='inventory_events')
    op.drop_index(op.f('ix_inventory_events_product_id'), table_name='inventory_events')
    op.drop_table('inventory_events')
    op.drop_table('approval_requests')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
